/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-07-28 08:18:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pahanaedu.model.Product;
import com.pahanaedu.model.User;
import java.text.SimpleDateFormat;

public final class add_005fedit_005fproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.pahanaedu.model.Product");
    _jspx_imports_classes.add("com.pahanaedu.model.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User loggedInUser = (User) session.getAttribute("user");
    if (loggedInUser == null || !loggedInUser.getRole().equals("ADMIN")) {
        response.sendRedirect("login.jsp");
        return;
    }
    
    Product product = (Product) request.getAttribute("product");
    if (product == null) {
        product = new Product();
    }
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String publicationDate = product.getPublicationDate() != null ? 
        dateFormat.format(product.getPublicationDate()) : "";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>");
      out.print( product.getProductId() == null ? "Add" : "Edit" );
      out.write(" Product</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Add your CSS styles here */\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>");
      out.print( product.getProductId() == null ? "Add" : "Edit" );
      out.write(" Product</h2>\r\n");
      out.write("    \r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"AddEditProductServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("        ");
 if (product.getProductId() != null) { 
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"product_id\" value=\"");
      out.print( product.getProductId() );
      out.write("\">\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Title:</label>\r\n");
      out.write("            <input type=\"text\" name=\"title\" value=\"");
      out.print( product.getTitle() != null ? product.getTitle() : "" );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Description:</label>\r\n");
      out.write("            <textarea name=\"description\" rows=\"4\">");
      out.print( product.getDescription() != null ? product.getDescription() : "" );
      out.write("</textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Author:</label>\r\n");
      out.write("            <input type=\"text\" name=\"author\" value=\"");
      out.print( product.getAuthor() != null ? product.getAuthor() : "" );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Publisher:</label>\r\n");
      out.write("            <input type=\"text\" name=\"publisher\" value=\"");
      out.print( product.getPublisher() != null ? product.getPublisher() : "" );
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Publication Date:</label>\r\n");
      out.write("            <input type=\"date\" name=\"publication_date\" value=\"");
      out.print( publicationDate );
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Category:</label>\r\n");
      out.write("            <input type=\"text\" name=\"category\" value=\"");
      out.print( product.getCategory() != null ? product.getCategory() : "" );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Price:</label>\r\n");
      out.write("            <input type=\"number\" name=\"price\" step=\"0.01\" min=\"0\" \r\n");
      out.write("                   value=\"");
      out.print( product.getPrice() != null ? product.getPrice() : "0.00" );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Stock Quantity:</label>\r\n");
      out.write("            <input type=\"number\" name=\"stock_quantity\" min=\"0\" \r\n");
      out.write("                   value=\"");
      out.print( product.getStockQuantity() );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("        <label>Image:</label>\r\n");
      out.write("        <input type=\"file\" name=\"image_file\" accept=\"image/*\">\r\n");
      out.write("        ");
 if (product.getImagePath() != null && !product.getImagePath().isEmpty()) { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() + "/images/" + product.getImagePath() );
      out.write("\"\r\n");
      out.write("                 width=\"100\" height=\"100\" alt=\"Product Image\">\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Discount Percentage:</label>\r\n");
      out.write("            <input type=\"number\" name=\"discount_percentage\" step=\"0.01\" min=\"0\" max=\"100\" \r\n");
      out.write("                   value=\"");
      out.print( product.getDiscountPercentage() != null ? product.getDiscountPercentage() : "0.00" );
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <input type=\"checkbox\" name=\"featured\" ");
      out.print( product.isFeatured() ? "checked" : "" );
      out.write(">\r\n");
      out.write("                Featured Product\r\n");
      out.write("            </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <input type=\"checkbox\" name=\"is_active\" ");
      out.print( product.isActive() ? "checked" : "" );
      out.write(">\r\n");
      out.write("                Active\r\n");
      out.write("            </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"margin-top: 20px;\">\r\n");
      out.write("            <input type=\"submit\" value=\"");
      out.print( product.getProductId() == null ? "Add" : "Update" );
      out.write(" Product\" class=\"btn\">\r\n");
      out.write("            <a href=\"ManageProductsServlet\" class=\"btn btn-secondary\">Cancel</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
