/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-19 10:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pahanaedu.model.User;
import com.pahanaedu.model.Product;
import java.util.List;

public final class create_005forder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.pahanaedu.model.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pahanaedu.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User loggedInUser = (User) session.getAttribute("user");
    if (loggedInUser == null || (!loggedInUser.getRole().equals("ADMIN") && !loggedInUser.getRole().equals("STAFF"))) {
        response.sendRedirect("login.jsp");
        return;
    }
    
    List<User> customers = (List<User>) request.getAttribute("customers");
    List<Product> products = (List<Product>) request.getAttribute("products");
    String error = (String) request.getAttribute("error");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Create New Order - Pahana Edu</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navigation */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            background: rgba(15, 15, 15, 0.95);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar.scrolled {\r\n");
      out.write("            background: rgba(15, 15, 15, 0.98);\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            filter: drop-shadow(0 0 20px rgba(255, 215, 0, 0.5));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -2px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            background: linear-gradient(90deg, #ffd700, #ff6b6b);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover::before {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            background: rgba(255, 215, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mobile-menu-btn {\r\n");
      out.write("            display: none;\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container */\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            margin: 100px auto 0;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ff6b6b 100%);\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h3 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 107, 107, 0.1), rgba(238, 90, 111, 0.1));\r\n");
      out.write("            border: 1px solid rgba(255, 107, 107, 0.3);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group select,\r\n");
      out.write("        .form-group input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            appearance: none; /* Remove default dropdown arrow */\r\n");
      out.write("            background-image: url('data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"%23ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"6 9 12 15 18 9\"></polyline></svg>');\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: right 1rem center;\r\n");
      out.write("            background-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group select:focus,\r\n");
      out.write("        .form-group input:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #ffd700;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(255, 215, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group select:hover,\r\n");
      out.write("        .form-group input[type=\"number\"]:hover {\r\n");
      out.write("            border-color: rgba(255, 215, 0, 0.3);\r\n");
      out.write("            background: rgba(255, 215, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group select option {\r\n");
      out.write("            background: #1a1a2e;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            padding: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.03);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-row:hover {\r\n");
      out.write("            border-color: rgba(255, 215, 0, 0.3);\r\n");
      out.write("            background: rgba(255, 215, 0, 0.05);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-select {\r\n");
      out.write("            flex: 3;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-input {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-input input[type=\"number\"] {\r\n");
      out.write("            -moz-appearance: textfield; /* Remove Firefox number spinners */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-input input::-webkit-outer-spin-button,\r\n");
      out.write("        .quantity-input input::-webkit-inner-spin-button {\r\n");
      out.write("            -webkit-appearance: none; /* Remove Chrome number spinners */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-input::after {\r\n");
      out.write("            content: 'Qty';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 1rem;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price-display {\r\n");
      out.write("            flex: 2;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stock-display {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: all 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%);\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(255, 215, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 215, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 2px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger {\r\n");
      out.write("            background: linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 107, 107, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #addProduct {\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .actions {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                margin: 80px 1rem 0;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            h1 {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .product-row {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: stretch;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .product-select,\r\n");
      out.write("            .quantity-input,\r\n");
      out.write("            .price-display,\r\n");
      out.write("            .stock-display {\r\n");
      out.write("                flex: none;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .quantity-input::after {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .actions {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-menu {\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                top: 80px;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                right: 0;\r\n");
      out.write("                background: rgba(15, 15, 15, 0.98);\r\n");
      out.write("                backdrop-filter: blur(20px);\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                padding: 2rem;\r\n");
      out.write("                display: none;\r\n");
      out.write("                border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("                z-index: 999;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-menu.active {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .mobile-menu-btn {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(50px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes ripple {\r\n");
      out.write("            to {\r\n");
      out.write("                transform: scale(4);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom scrollbar */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700, #ff6b6b);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #ffed4e, #ff6b6b);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar\" id=\"navbar\">\r\n");
      out.write("        <div class=\"nav-container\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"logo\">\r\n");
      out.write("                📖 Pahana Edu\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"nav-menu\" id=\"navMenu\">\r\n");
      out.write("                <li><a href=\"index.jsp\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp#features\" class=\"nav-link\">Features</a></li>\r\n");
      out.write("                <li><a href=\"store\" class=\"nav-link\">Store</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp#services\" class=\"nav-link\">Services</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp#contact\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"user-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( loggedInUser.getRole().equals("ADMIN") ? "admin_dashboard.jsp" : "staff_dashboard.jsp" );
      out.write("\" \r\n");
      out.write("                   class=\"btn btn-secondary\" style=\"padding: 0.5rem 1rem; font-size: 0.9rem; text-decoration: none;\">\r\n");
      out.write("                    👤 ");
      out.print( loggedInUser.getFirstName() );
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"LogoutServlet\" class=\"btn btn-danger\" style=\"padding: 0.5rem 1rem; font-size: 0.9rem; text-decoration: none;\" \r\n");
      out.write("                   onclick=\"return confirm('Are you sure you want to logout?')\">\r\n");
      out.write("                    🚪 Logout\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"mobile-menu-btn\" id=\"mobileMenuBtn\">☰</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Create New Order</h1>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if (error != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert-error\">\r\n");
      out.write("                ");
      out.print( error );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"ManageOrdersServlet\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"create\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"customerId\">Customer:</label>\r\n");
      out.write("                <select id=\"customerId\" name=\"customerId\" required>\r\n");
      out.write("                    <option value=\"\">Select Customer</option>\r\n");
      out.write("                    ");
 for (User customer : customers) { 
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( customer.getId() );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( customer.getFirstName() );
      out.write(' ');
      out.print( customer.getLastName() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( customer.getEmail() );
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <h3>Order Items</h3>\r\n");
      out.write("            <button type=\"button\" id=\"addProduct\" class=\"btn btn-primary\">Add Product</button>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"productContainer\">\r\n");
      out.write("                <!-- Product rows will be added here -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"actions\">\r\n");
      out.write("                <input type=\"submit\" value=\"Create Order\" class=\"btn btn-primary\">\r\n");
      out.write("                <a href=\"ManageOrdersServlet\" class=\"btn btn-secondary\">Cancel</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        const products = [\r\n");
      out.write("            ");
 for (Product product : products) { 
      out.write("\r\n");
      out.write("                {\r\n");
      out.write("                    id: ");
      out.print( product.getProductId() );
      out.write(",\r\n");
      out.write("                    title: '");
      out.print( product.getTitle().replace("'", "\\'") );
      out.write("',\r\n");
      out.write("                    author: '");
      out.print( product.getAuthor().replace("'", "\\'") );
      out.write("',\r\n");
      out.write("                    price: ");
      out.print( product.getPrice() );
      out.write(",\r\n");
      out.write("                    discount: ");
      out.print( product.getDiscountPercentage() );
      out.write(",\r\n");
      out.write("                    stock: ");
      out.print( product.getStockQuantity() );
      out.write("\r\n");
      out.write("                },\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        ];\r\n");
      out.write("        \r\n");
      out.write("        let productCounter = 0;\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById('addProduct').addEventListener('click', function() {\r\n");
      out.write("            addProductRow();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function addProductRow() {\r\n");
      out.write("            const container = document.getElementById('productContainer');\r\n");
      out.write("            const rowId = 'productRow_' + productCounter;\r\n");
      out.write("            \r\n");
      out.write("            const row = document.createElement('div');\r\n");
      out.write("            row.className = 'product-row';\r\n");
      out.write("            row.id = rowId;\r\n");
      out.write("            \r\n");
      out.write("            // Product select\r\n");
      out.write("            const selectDiv = document.createElement('div');\r\n");
      out.write("            selectDiv.className = 'product-select';\r\n");
      out.write("            \r\n");
      out.write("            const select = document.createElement('select');\r\n");
      out.write("            select.name = 'productId';\r\n");
      out.write("            select.required = true;\r\n");
      out.write("            select.addEventListener('change', function() { updateProductInfo(rowId); });\r\n");
      out.write("            \r\n");
      out.write("            const defaultOption = document.createElement('option');\r\n");
      out.write("            defaultOption.value = '';\r\n");
      out.write("            defaultOption.textContent = 'Select Product';\r\n");
      out.write("            select.appendChild(defaultOption);\r\n");
      out.write("            \r\n");
      out.write("            products.forEach(product => {\r\n");
      out.write("                const option = document.createElement('option');\r\n");
      out.write("                option.value = product.id;\r\n");
      out.write("                option.textContent = `${product.title} by ${product.author} - $${product.price.toFixed(2)}`;\r\n");
      out.write("                option.dataset.price = product.price;\r\n");
      out.write("                option.dataset.discount = product.discount;\r\n");
      out.write("                option.dataset.stock = product.stock;\r\n");
      out.write("                select.appendChild(option);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            selectDiv.appendChild(select);\r\n");
      out.write("            row.appendChild(selectDiv);\r\n");
      out.write("            \r\n");
      out.write("            // Quantity input\r\n");
      out.write("            const quantityDiv = document.createElement('div');\r\n");
      out.write("            quantityDiv.className = 'quantity-input';\r\n");
      out.write("            \r\n");
      out.write("            const quantityInput = document.createElement('input');\r\n");
      out.write("            quantityInput.type = 'number';\r\n");
      out.write("            quantityInput.name = 'quantity';\r\n");
      out.write("            quantityInput.min = '1';\r\n");
      out.write("            quantityInput.value = '1';\r\n");
      out.write("            quantityInput.required = true;\r\n");
      out.write("            quantityInput.addEventListener('input', function() { updateProductInfo(rowId); });\r\n");
      out.write("            \r\n");
      out.write("            quantityDiv.appendChild(quantityInput);\r\n");
      out.write("            row.appendChild(quantityDiv);\r\n");
      out.write("            \r\n");
      out.write("            // Stock display\r\n");
      out.write("            const stockDiv = document.createElement('div');\r\n");
      out.write("            stockDiv.className = 'stock-display';\r\n");
      out.write("            stockDiv.id = rowId + '_stock';\r\n");
      out.write("            stockDiv.textContent = 'Stock: 0';\r\n");
      out.write("            row.appendChild(stockDiv);\r\n");
      out.write("            \r\n");
      out.write("            // Price display\r\n");
      out.write("            const priceDiv = document.createElement('div');\r\n");
      out.write("            priceDiv.className = 'price-display';\r\n");
      out.write("            priceDiv.id = rowId + '_price';\r\n");
      out.write("            priceDiv.textContent = 'Total: $0.00';\r\n");
      out.write("            row.appendChild(priceDiv);\r\n");
      out.write("            \r\n");
      out.write("            // Remove button\r\n");
      out.write("            const removeDiv = document.createElement('div');\r\n");
      out.write("            \r\n");
      out.write("            const removeButton = document.createElement('button');\r\n");
      out.write("            removeButton.type = 'button';\r\n");
      out.write("            removeButton.className = 'btn btn-danger';\r\n");
      out.write("            removeButton.textContent = 'Remove';\r\n");
      out.write("            removeButton.addEventListener('click', function() {\r\n");
      out.write("                container.removeChild(row);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            removeDiv.appendChild(removeButton);\r\n");
      out.write("            row.appendChild(removeDiv);\r\n");
      out.write("            \r\n");
      out.write("            container.appendChild(row);\r\n");
      out.write("            productCounter++;\r\n");
      out.write("            \r\n");
      out.write("            // Observe the new row for animation\r\n");
      out.write("            row.style.opacity = '0';\r\n");
      out.write("            row.style.transform = 'translateY(30px)';\r\n");
      out.write("            row.style.transition = 'all 0.6s ease-out';\r\n");
      out.write("            observer.observe(row);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function updateProductInfo(rowId) {\r\n");
      out.write("            const row = document.getElementById(rowId);\r\n");
      out.write("            const select = row.querySelector('select');\r\n");
      out.write("            const quantityInput = row.querySelector('input[type=\"number\"]');\r\n");
      out.write("            const stockDisplay = document.getElementById(rowId + '_stock');\r\n");
      out.write("            const priceDisplay = document.getElementById(rowId + '_price');\r\n");
      out.write("            \r\n");
      out.write("            if (select.value && quantityInput.value) {\r\n");
      out.write("                const selectedOption = select.options[select.selectedIndex];\r\n");
      out.write("                const price = parseFloat(selectedOption.dataset.price);\r\n");
      out.write("                const discount = parseFloat(selectedOption.dataset.discount);\r\n");
      out.write("                const stock = parseInt(selectedOption.dataset.stock);\r\n");
      out.write("                const quantity = parseInt(quantityInput.value);\r\n");
      out.write("                \r\n");
      out.write("                // Update stock display\r\n");
      out.write("                stockDisplay.textContent = `Stock: ${stock}`;\r\n");
      out.write("                \r\n");
      out.write("                // Validate quantity against stock\r\n");
      out.write("                if (quantity > stock) {\r\n");
      out.write("                    alert(`Only ${stock} items available in stock`);\r\n");
      out.write("                    quantityInput.value = stock;\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                // Calculate and display price\r\n");
      out.write("                const discountedPrice = price * (1 - (discount / 100));\r\n");
      out.write("                const total = discountedPrice * quantity;\r\n");
      out.write("                \r\n");
      out.write("                let priceText = `Total: $${total.toFixed(2)}`;\r\n");
      out.write("                if (discount > 0) {\r\n");
      out.write("                    priceText += ` ($${price.toFixed(2)} x ${quantity} - ${discount}% off)`;\r\n");
      out.write("                } else {\r\n");
      out.write("                    priceText += ` ($${price.toFixed(2)} x ${quantity})`;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                priceDisplay.textContent = priceText;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Add first product row by default\r\n");
      out.write("        window.onload = function() {\r\n");
      out.write("            addProductRow();\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Navbar scroll effect\r\n");
      out.write("        window.addEventListener('scroll', function() {\r\n");
      out.write("            const navbar = document.getElementById('navbar');\r\n");
      out.write("            if (window.scrollY > 100) {\r\n");
      out.write("                navbar.classList.add('scrolled');\r\n");
      out.write("            } else {\r\n");
      out.write("                navbar.classList.remove('scrolled');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Mobile menu toggle\r\n");
      out.write("        document.getElementById('mobileMenuBtn').addEventListener('click', function() {\r\n");
      out.write("            const navMenu = document.getElementById('navMenu');\r\n");
      out.write("            navMenu.classList.toggle('active');\r\n");
      out.write("            this.innerHTML = navMenu.classList.contains('active') ? '✕' : '☰';\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Close mobile menu when clicking on a link\r\n");
      out.write("        document.querySelectorAll('.nav-link').forEach(link => {\r\n");
      out.write("            link.addEventListener('click', function() {\r\n");
      out.write("                const navMenu = document.getElementById('navMenu');\r\n");
      out.write("                const mobileMenuBtn = document.getElementById('mobileMenuBtn');\r\n");
      out.write("                navMenu.classList.remove('active');\r\n");
      out.write("                mobileMenuBtn.innerHTML = '☰';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Smooth scrolling for navigation links\r\n");
      out.write("        document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\r\n");
      out.write("            anchor.addEventListener('click', function (e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                const target = document.querySelector(this.getAttribute('href'));\r\n");
      out.write("                if (target) {\r\n");
      out.write("                    target.scrollIntoView({\r\n");
      out.write("                        behavior: 'smooth',\r\n");
      out.write("                        block: 'start'\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Button ripple effect\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const buttons = document.querySelectorAll('.btn');\r\n");
      out.write("            buttons.forEach(button => {\r\n");
      out.write("                button.addEventListener('click', function(e) {\r\n");
      out.write("                    const ripple = document.createElement('span');\r\n");
      out.write("                    const rect = this.getBoundingClientRect();\r\n");
      out.write("                    const size = Math.max(rect.width, rect.height);\r\n");
      out.write("                    const x = e.clientX - rect.left - size / 2;\r\n");
      out.write("                    const y = e.clientY - rect.top - size / 2;\r\n");
      out.write("                    \r\n");
      out.write("                    ripple.style.cssText = `\r\n");
      out.write("                        position: absolute;\r\n");
      out.write("                        width: ${size}px;\r\n");
      out.write("                        height: ${size}px;\r\n");
      out.write("                        left: ${x}px;\r\n");
      out.write("                        top: ${y}px;\r\n");
      out.write("                        background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        transform: scale(0);\r\n");
      out.write("                        animation: ripple 0.6s linear;\r\n");
      out.write("                        pointer-events: none;\r\n");
      out.write("                        z-index: 10;\r\n");
      out.write("                    `;\r\n");
      out.write("                    \r\n");
      out.write("                    this.appendChild(ripple);\r\n");
      out.write("                    \r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        ripple.remove();\r\n");
      out.write("                    }, 600);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Intersection Observer for animations\r\n");
      out.write("        const observerOptions = {\r\n");
      out.write("            threshold: 0.1,\r\n");
      out.write("            rootMargin: '0px 0px -50px 0px'\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        const observer = new IntersectionObserver(function(entries) {\r\n");
      out.write("            entries.forEach(entry => {\r\n");
      out.write("                if (entry.isIntersecting) {\r\n");
      out.write("                    entry.target.style.opacity = '1';\r\n");
      out.write("                    entry.target.style.transform = 'translateY(0)';\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }, observerOptions);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
