/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-04 09:03:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pahanaedu.model.User;

public final class edit_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.pahanaedu.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    
    boolean isAdmin = "ADMIN".equals(user.getRole());
    boolean isStaff = "STAFF".equals(user.getRole());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Edit Profile - Pahana Edu</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navigation */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            background: rgba(15, 15, 15, 0.95);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar.scrolled {\r\n");
      out.write("            background: rgba(15, 15, 15, 0.98);\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            filter: drop-shadow(0 0 20px rgba(255, 215, 0, 0.5));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -2px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            background: linear-gradient(90deg, #ffd700, #ff6b6b);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover::before {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            background: rgba(255, 215, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mobile-menu-btn {\r\n");
      out.write("            display: none;\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Content */\r\n");
      out.write("        .main-content {\r\n");
      out.write("            padding: 8rem 0;\r\n");
      out.write("            background: linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-container {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            padding: 2.5rem;\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ff6b6b 100%);\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-subtitle {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .role-indicator {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            background: rgba(255, 215, 0, 0.1);\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input,\r\n");
      out.write("        .form-group textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input:focus,\r\n");
      out.write("        .form-group textarea:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #ffd700;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(255, 215, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .readonly-field {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            cursor: not-allowed;\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: all 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%);\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(255, 215, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 215, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 107, 107, 0.1), rgba(255, 107, 107, 0.05));\r\n");
      out.write("            border: 1px solid rgba(255, 107, 107, 0.3);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success {\r\n");
      out.write("            background: linear-gradient(135deg, #4CAF50, #45a049);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            animation: slideInUp 0.5s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .password-section {\r\n");
      out.write("            margin-top: 3rem;\r\n");
      out.write("            padding-top: 2rem;\r\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .password-section h3 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 2px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger {\r\n");
      out.write("            background: linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 107, 107, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-info {\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4 0%, #44a08d 100%);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-info:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(78, 205, 196, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        .footer {\r\n");
      out.write("            background: #0a0a0a;\r\n");
      out.write("            padding: 4rem 0 2rem;\r\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-content {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 3rem;\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-section h4 {\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-section p,\r\n");
      out.write("        .footer-section a {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            line-height: 1.8;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-section a:hover {\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-section ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-section ul li {\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social-links a {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social-links a:hover {\r\n");
      out.write("            background: #ffd700;\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-bottom {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-top: 2rem;\r\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(50px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes ripple {\r\n");
      out.write("            to {\r\n");
      out.write("                transform: scale(4);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes spin {\r\n");
      out.write("            from { transform: rotate(0deg); }\r\n");
      out.write("            to { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Scroll to top button */\r\n");
      out.write("        .scroll-top {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 2rem;\r\n");
      out.write("            right: 2rem;\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%);\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .scroll-top.visible {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .scroll-top:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(255, 215, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .nav-menu {\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                top: 80px;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                right: 0;\r\n");
      out.write("                background: rgba(15, 15, 15, 0.98);\r\n");
      out.write("                backdrop-filter: blur(20px);\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                padding: 2rem;\r\n");
      out.write("                display: none;\r\n");
      out.write("                border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("                z-index: 999;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-menu.active {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .mobile-menu-btn {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 0 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-container {\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .user-menu {\r\n");
      out.write("                gap: 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom scrollbar */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700, #ff6b6b);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #ffed4e, #ff6b6b);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Page Loader */\r\n");
      out.write("        .page-loader {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("            transition: opacity 0.5s ease, visibility 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-loader.hidden {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loader-content {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loader-icon {\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            animation: spin 2s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Page Loader -->\r\n");
      out.write("    <div class=\"page-loader\" id=\"pageLoader\">\r\n");
      out.write("        <div class=\"loader-content\">\r\n");
      out.write("            <div class=\"loader-icon\">📚</div>\r\n");
      out.write("            <h3>Loading Pahana Edu...</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar\" id=\"navbar\">\r\n");
      out.write("        <div class=\"nav-container\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"logo\">\r\n");
      out.write("                📖 Pahana Edu\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"nav-menu\" id=\"navMenu\">\r\n");
      out.write("                <li><a href=\"index.jsp#home\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp#features\" class=\"nav-link\">Features</a></li>\r\n");
      out.write("                <li><a href=\"store\" class=\"nav-link\">Store</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp#services\" class=\"nav-link\">Services</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp#contact\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"user-menu\">\r\n");
      out.write("                ");
 if (user != null) { 
      out.write("\r\n");
      out.write("                    ");
 
                        String roleBasedLink;
                        if (isAdmin) {
                            roleBasedLink = "admin_dashboard.jsp";
                        } else if (isStaff) {
                            roleBasedLink = "staff_dashboard.jsp";
                        } else {
                            roleBasedLink = "edit_profile.jsp";
                        }
                    
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print( roleBasedLink );
      out.write("\" class=\"btn btn-secondary\" style=\"padding: 0.5rem 1rem; font-size: 0.9rem; text-decoration: none;\">\r\n");
      out.write("                        👤 ");
      out.print( user.getFirstName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"LogoutServlet\" class=\"btn btn-danger\" style=\"padding: 0.5rem 1rem; font-size: 0.9rem; text-decoration: none;\" \r\n");
      out.write("                       onclick=\"return confirm('Are you sure you want to logout?')\">\r\n");
      out.write("                        🚪 Logout\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <a href=\"login.jsp\" class=\"btn btn-info\" style=\"padding: 0.5rem 1rem; font-size: 0.9rem; text-decoration: none;\">\r\n");
      out.write("                        🔑 Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"mobile-menu-btn\" id=\"mobileMenuBtn\">☰</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <section class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <h2 class=\"section-title\">Edit Your Profile</h2>\r\n");
      out.write("                <p class=\"section-subtitle\">\r\n");
      out.write("                    Update your personal information and manage your account settings\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"profile-container\">\r\n");
      out.write("                <div class=\"role-indicator\">\r\n");
      out.write("                    ");
 if (isAdmin) { 
      out.write("\r\n");
      out.write("                        ADMINISTRATOR PROFILE\r\n");
      out.write("                    ");
 } else if (isStaff) { 
      out.write("\r\n");
      out.write("                        STAFF PROFILE\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        CUSTOMER PROFILE\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (request.getParameter("success") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"success\">");
      out.print( request.getParameter("success") );
      out.write("</div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <form action=\"ProfileServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"updateProfile\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\">Email:</label>\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( user.getEmail() );
      out.write("\" required readonly class=\"readonly-field\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"firstName\">First Name:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"firstName\" name=\"first_name\" value=\"");
      out.print( user.getFirstName() );
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"lastName\" name=\"last_name\" value=\"");
      out.print( user.getLastName() );
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"address\">Address:</label>\r\n");
      out.write("                        <input type=\"text\" id=\"address\" name=\"address\" value=\"");
      out.print( user.getAddress() != null ? user.getAddress() : "" );
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"telephone\">Phone Number:</label>\r\n");
      out.write("                        <input type=\"tel\" id=\"telephone\" name=\"telephone\" value=\"");
      out.print( user.getTelephone() != null ? user.getTelephone() : "" );
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if ("CUSTOMER".equals(user.getRole())) { 
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"unitsConsumed\">Units Consumed:</label>\r\n");
      out.write("                            <input type=\"number\" id=\"unitsConsumed\" name=\"units_consumed\" \r\n");
      out.write("                                   value=\"");
      out.print( user.getUnitsConsumed() );
      out.write("\" min=\"0\"\r\n");
      out.write("                                   class=\"readonly-field\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Update Profile</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"password-section\">\r\n");
      out.write("                    <h3>Change Password</h3>\r\n");
      out.write("                    <form action=\"ProfileServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"changePassword\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"currentPassword\">Current Password:</label>\r\n");
      out.write("                            <input type=\"password\" id=\"currentPassword\" name=\"currentPassword\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"newPassword\">New Password:</label>\r\n");
      out.write("                            <input type=\"password\" id=\"newPassword\" name=\"newPassword\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"confirmPassword\">Confirm New Password:</label>\r\n");
      out.write("                            <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Change Password</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h4>Pahana Edu</h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Your premier destination for educational resources and learning experiences. \r\n");
      out.write("                        We're passionate about connecting learners with their next great educational adventure.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"social-links\">\r\n");
      out.write("                        <a href=\"#\" title=\"Facebook\">📘</a>\r\n");
      out.write("                        <a href=\"#\" title=\"Twitter\">🐦</a>\r\n");
      out.write("                        <a href=\"#\" title=\"Instagram\">📷</a>\r\n");
      out.write("                        <a href=\"#\" title=\"LinkedIn\">💼</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h4>Quick Links</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"index.jsp#home\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"store\">Browse Resources</a></li>\r\n");
      out.write("                        ");
 if (user != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"ManageOrdersServlet?action=history\">Order History</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <li><a href=\"index.jsp#services\">Services</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp#contact\">Contact Us</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h4>Categories</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"store?category=fiction\">Fiction</a></li>\r\n");
      out.write("                        <li><a href=\"store?category=non-fiction\">Non-Fiction</a></li>\r\n");
      out.write("                        <li><a href=\"store?category=science\">Science & Technology</a></li>\r\n");
      out.write("                        <li><a href=\"store?category=biography\">Biography</a></li>\r\n");
      out.write("                        <li><a href=\"store?category=children\">Children's Books</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h4>Customer Service</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"index.jsp#contact\">Help Center</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp#services\">Shipping Info</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp#services\">Returns & Refunds</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp#contact\">Privacy Policy</a></li>\r\n");
      out.write("                        <li><a href=\"index.jsp#contact\">Terms of Service</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2025 Pahana Edu. All rights reserved. Made with ❤️ for learners.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button -->\r\n");
      out.write("    <button class=\"scroll-top\" id=\"scrollTop\">↑</button>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Page loader\r\n");
      out.write("        window.addEventListener('load', function() {\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                document.getElementById('pageLoader').classList.add('hidden');\r\n");
      out.write("            }, 1500);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Navbar scroll effect\r\n");
      out.write("        window.addEventListener('scroll', function() {\r\n");
      out.write("            const navbar = document.getElementById('navbar');\r\n");
      out.write("            const scrollTop = document.getElementById('scrollTop');\r\n");
      out.write("            \r\n");
      out.write("            if (window.scrollY > 100) {\r\n");
      out.write("                navbar.classList.add('scrolled');\r\n");
      out.write("                scrollTop.classList.add('visible');\r\n");
      out.write("            } else {\r\n");
      out.write("                navbar.classList.remove('scrolled');\r\n");
      out.write("                scrollTop.classList.remove('visible');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Mobile menu toggle\r\n");
      out.write("        document.getElementById('mobileMenuBtn').addEventListener('click', function() {\r\n");
      out.write("            const navMenu = document.getElementById('navMenu');\r\n");
      out.write("            navMenu.classList.toggle('active');\r\n");
      out.write("            \r\n");
      out.write("            this.innerHTML = navMenu.classList.contains('active') ? '✕' : '☰';\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Close mobile menu when clicking on a link\r\n");
      out.write("        document.querySelectorAll('.nav-link').forEach(link => {\r\n");
      out.write("            link.addEventListener('click', function() {\r\n");
      out.write("                const navMenu = document.getElementById('navMenu');\r\n");
      out.write("                const mobileMenuBtn = document.getElementById('mobileMenuBtn');\r\n");
      out.write("                navMenu.classList.remove('active');\r\n");
      out.write("                mobileMenuBtn.innerHTML = '☰';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Smooth scrolling for navigation links\r\n");
      out.write("        document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\r\n");
      out.write("            anchor.addEventListener('click', function (e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                const target = document.querySelector(this.getAttribute('href'));\r\n");
      out.write("                if (target) {\r\n");
      out.write("                    target.scrollIntoView({\r\n");
      out.write("                        behavior: 'smooth',\r\n");
      out.write("                        block: 'start'\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Scroll to top functionality\r\n");
      out.write("        document.getElementById('scrollTop').addEventListener('click', function() {\r\n");
      out.write("            window.scrollTo({\r\n");
      out.write("                top: 0,\r\n");
      out.write("                behavior: 'smooth'\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Enhanced button interactions with ripple effect\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const buttons = document.querySelectorAll('.btn');\r\n");
      out.write("            buttons.forEach(button => {\r\n");
      out.write("                button.addEventListener('click', function(e) {\r\n");
      out.write("                    const ripple = document.createElement('span');\r\n");
      out.write("                    const rect = this.getBoundingClientRect();\r\n");
      out.write("                    const size = Math.max(rect.width, rect.height);\r\n");
      out.write("                    const x = e.clientX - rect.left - size / 2;\r\n");
      out.write("                    const y = e.clientY - rect.top - size / 2;\r\n");
      out.write("                    \r\n");
      out.write("                    ripple.style.cssText = `\r\n");
      out.write("                        position: absolute;\r\n");
      out.write("                        width: ${size}px;\r\n");
      out.write("                        height: ${size}px;\r\n");
      out.write("                        left: ${x}px;\r\n");
      out.write("                        top: ${y}px;\r\n");
      out.write("                        background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        transform: scale(0);\r\n");
      out.write("                        animation: ripple 0.6s linear;\r\n");
      out.write("                        pointer-events: none;\r\n");
      out.write("                        z-index: 10;\r\n");
      out.write("                    `;\r\n");
      out.write("                    \r\n");
      out.write("                    this.appendChild(ripple);\r\n");
      out.write("                    \r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        ripple.remove();\r\n");
      out.write("                    }, 600);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Intersection Observer for animations\r\n");
      out.write("        const observerOptions = {\r\n");
      out.write("            threshold: 0.1,\r\n");
      out.write("            rootMargin: '0px 0px -50px 0px'\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        const observer = new IntersectionObserver(function(entries) {\r\n");
      out.write("            entries.forEach(entry => {\r\n");
      out.write("                if (entry.isIntersecting) {\r\n");
      out.write("                    entry.target.style.opacity = '1';\r\n");
      out.write("                    entry.target.style.transform = 'translateY(0)';\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }, observerOptions);\r\n");
      out.write("\r\n");
      out.write("        document.querySelectorAll('.profile-container').forEach(el => {\r\n");
      out.write("            el.style.opacity = '0';\r\n");
      out.write("            el.style.transform = 'translateY(30px)';\r\n");
      out.write("            el.style.transition = 'all 0.6s ease-out';\r\n");
      out.write("            observer.observe(el);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
