/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-19 10:43:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forgot_002dpassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Forgot Password - Pahana Edu</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container */\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ff6b6b 100%);\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 107, 107, 0.1), rgba(238, 90, 111, 0.1));\r\n");
      out.write("            border: 1px solid rgba(255, 107, 107, 0.3);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(76, 175, 80, 0.1), rgba(69, 160, 73, 0.1));\r\n");
      out.write("            border: 1px solid rgba(76, 175, 80, 0.3);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #ffd700;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(255, 215, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input:hover {\r\n");
      out.write("            border-color: rgba(255, 215, 0, 0.3);\r\n");
      out.write("            background: rgba(255, 215, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%);\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(255, 215, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 215, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: all 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link:hover {\r\n");
      out.write("            color: #ffed4e;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                margin: 1rem;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(50px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes ripple {\r\n");
      out.write("            to {\r\n");
      out.write("                transform: scale(4);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom scrollbar */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700, #ff6b6b);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #ffed4e, #ff6b6b);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Forgot Password</h2>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if (request.getParameter("message") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"success\">");
      out.print( request.getParameter("message") );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"password-reset\" method=\"post\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"email\">Email Address:</label>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">Send Reset Link</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <p><a href=\"login.jsp\" class=\"back-link\">Back to Login</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Button ripple effect\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const buttons = document.querySelectorAll('.btn');\r\n");
      out.write("            buttons.forEach(button => {\r\n");
      out.write("                button.addEventListener('click', function(e) {\r\n");
      out.write("                    const ripple = document.createElement('span');\r\n");
      out.write("                    const rect = this.getBoundingClientRect();\r\n");
      out.write("                    const size = Math.max(rect.width, rect.height);\r\n");
      out.write("                    const x = e.clientX - rect.left - size / 2;\r\n");
      out.write("                    const y = e.clientY - rect.top - size / 2;\r\n");
      out.write("                    \r\n");
      out.write("                    ripple.style.cssText = `\r\n");
      out.write("                        position: absolute;\r\n");
      out.write("                        width: ${size}px;\r\n");
      out.write("                        height: ${size}px;\r\n");
      out.write("                        left: ${x}px;\r\n");
      out.write("                        top: ${y}px;\r\n");
      out.write("                        background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        transform: scale(0);\r\n");
      out.write("                        animation: ripple 0.6s linear;\r\n");
      out.write("                        pointer-events: none;\r\n");
      out.write("                        z-index: 10;\r\n");
      out.write("                    `;\r\n");
      out.write("                    \r\n");
      out.write("                    this.appendChild(ripple);\r\n");
      out.write("                    \r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        ripple.remove();\r\n");
      out.write("                    }, 600);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Intersection Observer for animations\r\n");
      out.write("        const observerOptions = {\r\n");
      out.write("            threshold: 0.1,\r\n");
      out.write("            rootMargin: '0px 0px -50px 0px'\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        const observer = new IntersectionObserver(function(entries) {\r\n");
      out.write("            entries.forEach(entry => {\r\n");
      out.write("                if (entry.isIntersecting) {\r\n");
      out.write("                    entry.target.style.opacity = '1';\r\n");
      out.write("                    entry.target.style.transform = 'translateY(0)';\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }, observerOptions);\r\n");
      out.write("\r\n");
      out.write("        // Observe container for animation\r\n");
      out.write("        const container = document.querySelector('.container');\r\n");
      out.write("        container.style.opacity = '0';\r\n");
      out.write("        container.style.transform = 'translateY(30px)';\r\n");
      out.write("        container.style.transition = 'all 0.6s ease-out';\r\n");
      out.write("        observer.observe(container);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
