/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-02 11:07:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Register - Chapter & Verse</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Register Section */\r\n");
      out.write("        .register-section {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 50%, #16213e 100%);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-section::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\"><defs><radialGradient id=\"grad\" cx=\"50%\" cy=\"50%\" r=\"50%\"><stop offset=\"0%\" style=\"stop-color:rgba(255,215,0,0.1);stop-opacity:1\" /><stop offset=\"100%\" style=\"stop-color:rgba(255,215,0,0);stop-opacity:0\" /></radialGradient></defs><circle cx=\"20\" cy=\"20\" r=\"2\" fill=\"url(%23grad)\"><animate attributeName=\"opacity\" values=\"0;1;0\" dur=\"3s\" repeatCount=\"indefinite\"/></circle><circle cx=\"80\" cy=\"40\" r=\"1.5\" fill=\"url(%23grad)\"><animate attributeName=\"opacity\" values=\"0;1;0\" dur=\"4s\" repeatCount=\"indefinite\" begin=\"1s\"/></circle><circle cx=\"40\" cy=\"80\" r=\"1\" fill=\"url(%23grad)\"><animate attributeName=\"opacity\" values=\"0;1;0\" dur=\"2s\" repeatCount=\"indefinite\" begin=\"2s\"/></circle></svg>') repeat;\r\n");
      out.write("            animation: float 20s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 600px; /* Increased from 450px to make the box wider */\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            padding: 3rem;\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-card::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(90deg, #ffd700, #ff6b6b, #4ecdc4);\r\n");
      out.write("            animation: shimmer 3s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-title {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ff6b6b 50%, #4ecdc4 100%);\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            animation: slideInUp 1s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-subtitle {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            animation: slideInUp 1s ease-out 0.2s both;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 1rem 1rem 1rem 3rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input:focus {\r\n");
      out.write("            border-color: #ffd700;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(255, 215, 0, 0.1);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input::placeholder {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-icon {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 1rem;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            margin-top: 0.75rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: all 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%);\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(255, 215, 0, 0.3);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 215, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 2px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 2rem 0;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider span {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            padding: 0 1rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-link a {\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-link a:hover {\r\n");
      out.write("            color: #ffed4e;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert {\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            animation: slideInUp 0.5s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(244, 67, 54, 0.2), rgba(244, 67, 54, 0.1));\r\n");
      out.write("            border: 1px solid rgba(244, 67, 54, 0.3);\r\n");
      out.write("            color: #f44336;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Back to home link */\r\n");
      out.write("        .back-home {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 1rem;\r\n");
      out.write("            right: 1rem;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(30px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0%, 100% { transform: translateY(0px); }\r\n");
      out.write("            50% { transform: translateY(-20px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes shimmer {\r\n");
      out.write("            0%, 100% { transform: scaleX(0); }\r\n");
      out.write("            50% { transform: scaleX(1); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .register-section {\r\n");
      out.write("                padding: 2rem 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .register-card {\r\n");
      out.write("                padding: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .register-title {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .back-home {\r\n");
      out.write("                position: static;\r\n");
      out.write("                margin-bottom: 1rem;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Loading animation */\r\n");
      out.write("        .page-loader {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("            transition: opacity 0.5s ease, visibility 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-loader.hidden {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loader-content {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loader-icon {\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            animation: spin 2s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes spin {\r\n");
      out.write("            from { transform: rotate(0deg); }\r\n");
      out.write("            to { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom scrollbar */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700, #ff6b6b);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #ffed4e, #ff6b6b);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Page Loader -->\r\n");
      out.write("    <div class=\"page-loader\" id=\"pageLoader\">\r\n");
      out.write("        <div class=\"loader-content\">\r\n");
      out.write("            <div class=\"loader-icon\">📚</div>\r\n");
      out.write("            <h3>Loading Chapter & Verse...</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Register Section -->\r\n");
      out.write("    <section class=\"register-section\">\r\n");
      out.write("        <div class=\"register-container\">\r\n");
      out.write("            <div class=\"register-card\">\r\n");
      out.write("                <div class=\"back-home\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"btn btn-secondary\" style=\"padding: 0.5rem 1rem; font-size: 0.9rem;\">\r\n");
      out.write("                        🏠 Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"register-header\">\r\n");
      out.write("                    <h1 class=\"register-title\">Create Your Account</h1>\r\n");
      out.write("                    <p class=\"register-subtitle\">Join our literary community today</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-error\">\r\n");
      out.write("                        ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form class=\"register-form\" action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\">Email</label>\r\n");
      out.write("                        <div class=\"input-icon\">📧</div>\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your email\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"password\">Password</label>\r\n");
      out.write("                        <div class=\"input-icon\">🔒</div>\r\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"confirmPassword\">Confirm Password</label>\r\n");
      out.write("                        <div class=\"input-icon\">🔒</div>\r\n");
      out.write("                        <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm your password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"firstName\">First Name</label>\r\n");
      out.write("                        <div class=\"input-icon\">👤</div>\r\n");
      out.write("                        <input type=\"text\" id=\"firstName\" name=\"first_name\" placeholder=\"Enter your first name\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"lastName\">Last Name</label>\r\n");
      out.write("                        <div class=\"input-icon\">👤</div>\r\n");
      out.write("                        <input type=\"text\" id=\"lastName\" name=\"last_name\" placeholder=\"Enter your last name\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"address\">Address</label>\r\n");
      out.write("                        <div class=\"input-icon\">🏠</div>\r\n");
      out.write("                        <input type=\"text\" id=\"address\" name=\"address\" placeholder=\"Enter your address\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"telephone\">Phone Number</label>\r\n");
      out.write("                        <div class=\"input-icon\">📞</div>\r\n");
      out.write("                        <input type=\"tel\" id=\"telephone\" name=\"telephone\" placeholder=\"Enter your phone number\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\" name=\"role\" value=\"CUSTOMER\">\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        📝 Register\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"divider\">\r\n");
      out.write("                    <span>or</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"login-link\">\r\n");
      out.write("                    Already have an account? <a href=\"login.jsp\">Login here</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Page loader\r\n");
      out.write("        window.addEventListener('load', function() {\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                document.getElementById('pageLoader').classList.add('hidden');\r\n");
      out.write("            }, 1000);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Enhanced button interactions with ripple effect\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const buttons = document.querySelectorAll('.btn');\r\n");
      out.write("            buttons.forEach(button => {\r\n");
      out.write("                button.addEventListener('click', function(e) {\r\n");
      out.write("                    // Create ripple effect\r\n");
      out.write("                    const ripple = document.createElement('span');\r\n");
      out.write("                    const rect = this.getBoundingClientRect();\r\n");
      out.write("                    const size = Math.max(rect.width, rect.height);\r\n");
      out.write("                    const x = e.clientX - rect.left - size / 2;\r\n");
      out.write("                    const y = e.clientY - rect.top - size / 2;\r\n");
      out.write("                    \r\n");
      out.write("                    ripple.style.cssText = `\r\n");
      out.write("                        position: absolute;\r\n");
      out.write("                        width: ${size}px;\r\n");
      out.write("                        height: ${size}px;\r\n");
      out.write("                        left: ${x}px;\r\n");
      out.write("                        top: ${y}px;\r\n");
      out.write("                        background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        transform: scale(0);\r\n");
      out.write("                        animation: ripple 0.6s linear;\r\n");
      out.write("                        pointer-events: none;\r\n");
      out.write("                        z-index: 10;\r\n");
      out.write("                    `;\r\n");
      out.write("                    \r\n");
      out.write("                    this.appendChild(ripple);\r\n");
      out.write("                    \r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        ripple.remove();\r\n");
      out.write("                    }, 600);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Add ripple animation keyframes\r\n");
      out.write("        const style = document.createElement('style');\r\n");
      out.write("        style.textContent = `\r\n");
      out.write("            @keyframes ripple {\r\n");
      out.write("                to {\r\n");
      out.write("                    transform: scale(4);\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        `;\r\n");
      out.write("        document.head.appendChild(style);\r\n");
      out.write("\r\n");
      out.write("        // Form validation and enhancement\r\n");
      out.write("        const registerForm = document.querySelector('.register-form');\r\n");
      out.write("        const inputs = document.querySelectorAll('input[type=\"text\"], input[type=\"password\"], input[type=\"email\"], input[type=\"tel\"]');\r\n");
      out.write("\r\n");
      out.write("        // Add focus/blur effects\r\n");
      out.write("        inputs.forEach(input => {\r\n");
      out.write("            input.addEventListener('focus', function() {\r\n");
      out.write("                this.parentElement.style.transform = 'translateY(-2px)';\r\n");
      out.write("                this.parentElement.style.transition = 'transform 0.3s ease';\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            input.addEventListener('blur', function() {\r\n");
      out.write("                this.parentElement.style.transform = 'translateY(0)';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Add some sparkle effects on form interaction\r\n");
      out.write("        inputs.forEach(input => {\r\n");
      out.write("            input.addEventListener('focus', function(e) {\r\n");
      out.write("                createSparkle(e.target.getBoundingClientRect().left + e.target.offsetWidth - 20, \r\n");
      out.write("                            e.target.getBoundingClientRect().top + 20);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function createSparkle(x, y) {\r\n");
      out.write("            const sparkle = document.createElement('div');\r\n");
      out.write("            sparkle.innerHTML = '✨';\r\n");
      out.write("            sparkle.style.cssText = `\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                left: ${x}px;\r\n");
      out.write("                top: ${y}px;\r\n");
      out.write("                font-size: ${Math.random() * 8 + 12}px;\r\n");
      out.write("                pointer-events: none;\r\n");
      out.write("                z-index: 10;\r\n");
      out.write("                animation: sparkleAnim 1.5s ease-out forwards;\r\n");
      out.write("            `;\r\n");
      out.write("            \r\n");
      out.write("            document.body.appendChild(sparkle);\r\n");
      out.write("            \r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                sparkle.remove();\r\n");
      out.write("            }, 1500);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Add sparkle animation\r\n");
      out.write("        const sparkleStyleSheet = document.createElement('style');\r\n");
      out.write("        sparkleStyleSheet.textContent = `\r\n");
      out.write("            @keyframes sparkleAnim {\r\n");
      out.write("                0% {\r\n");
      out.write("                    transform: scale(0) rotate(0deg);\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                }\r\n");
      out.write("                50% {\r\n");
      out.write("                    transform: scale(1) rotate(180deg);\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                }\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: scale(0) rotate(360deg);\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        `;\r\n");
      out.write("        document.head.appendChild(sparkleStyleSheet);\r\n");
      out.write("\r\n");
      out.write("        // Keyboard shortcuts\r\n");
      out.write("        document.addEventListener('keydown', function(e) {\r\n");
      out.write("            // Enter key to submit form when focused on any input\r\n");
      out.write("            if (e.key === 'Enter' && (e.target.tagName === 'INPUT')) {\r\n");
      out.write("                const submitBtn = document.querySelector('.btn-primary');\r\n");
      out.write("                if (submitBtn) {\r\n");
      out.write("                    submitBtn.click();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
