/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-19 10:17:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pahanaedu.model.Order;
import com.pahanaedu.model.User;
import com.pahanaedu.model.OrderItem;

public final class view_005forder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.pahanaedu.model.OrderItem");
    _jspx_imports_classes.add("com.pahanaedu.model.User");
    _jspx_imports_classes.add("com.pahanaedu.model.Order");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Order order = (Order) request.getAttribute("order");
    String error = (String) request.getAttribute("error");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Order Details - Pahana Edu</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Content */\r\n");
      out.write("        .main-content {\r\n");
      out.write("            padding: 8rem 0;\r\n");
      out.write("            background: linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ff6b6b 100%);\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-subtitle {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Alert Messages */\r\n");
      out.write("        .alert {\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            animation: slideInUp 0.5s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 107, 107, 0.1), rgba(255, 107, 107, 0.05));\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 1px solid rgba(255, 107, 107, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Section Card */\r\n");
      out.write("        .section-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-card:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(255, 215, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-card h3 {\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Button Styles */\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            padding: 0.8rem 1.5rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: all 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700 0%, #ffed4e 100%);\r\n");
      out.write("            color: #0f0f0f;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(255, 215, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(255, 215, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-success {\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4 0%, #44a08d 100%);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-success:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(78, 205, 196, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 2px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-print {\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4 0%, #44a08d 100%);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-print:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(78, 205, 196, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Order Info Section */\r\n");
      out.write("        .order-info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-section {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            min-width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-section h3 {\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            padding-bottom: 0.5rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            margin-bottom: 0.8rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Table Styles */\r\n");
      out.write("        .table-container {\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background: rgba(255, 215, 0, 0.1);\r\n");
      out.write("            color: #ffd700;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tbody tr:hover {\r\n");
      out.write("            background: rgba(255, 215, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .total-row {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            background: rgba(255, 215, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .discount {\r\n");
      out.write("            color: #4ecdc4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Actions */\r\n");
      out.write("        .actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(50px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom scrollbar */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: #0f0f0f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: linear-gradient(135deg, #ffd700, #ff6b6b);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #ffed4e, #ff6b6b);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 0 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-card {\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .order-info {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: stretch;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            th, td {\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Print-specific styles */\r\n");
      out.write("        @media print {\r\n");
      out.write("            .no-print {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body {\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                color: #000;\r\n");
      out.write("                font-size: 12pt;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container {\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("                border: none;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-card {\r\n");
      out.write("                background: none;\r\n");
      out.write("                backdrop-filter: none;\r\n");
      out.write("                border: none;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-title {\r\n");
      out.write("                background: none;\r\n");
      out.write("                -webkit-text-fill-color: #000;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .info-label, th, td {\r\n");
      out.write("                color: #000;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .table-container {\r\n");
      out.write("                background: none;\r\n");
      out.write("                border: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            table {\r\n");
      out.write("                border: 1px solid #000;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            th, td {\r\n");
      out.write("                border: 1px solid #000;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .total-row {\r\n");
      out.write("                background: none;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <section class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <h2 class=\"section-title\">Order Details - #");
      out.print( order.getOrderId() );
      out.write("</h2>\r\n");
      out.write("                <p class=\"section-subtitle\">Bill Number: ");
      out.print( order.getBillNumber() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (error != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert alert-error\">\r\n");
      out.write("                    ❌ ");
      out.print( error );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"section-card\">\r\n");
      out.write("                <div class=\"order-info\">\r\n");
      out.write("                    <div class=\"info-section\">\r\n");
      out.write("                        <h3>👤 Customer Information</h3>\r\n");
      out.write("                        <div class=\"info-row\">\r\n");
      out.write("                            <div class=\"info-label\">Name:</div>\r\n");
      out.write("                            <div>");
      out.print( order.getCustomer().getFirstName() );
      out.write(' ');
      out.print( order.getCustomer().getLastName() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-row\">\r\n");
      out.write("                            <div class=\"info-label\">Email:</div>\r\n");
      out.write("                            <div>");
      out.print( order.getCustomer().getEmail() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 if (order.getCustomer().getTelephone() != null && !order.getCustomer().getTelephone().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"info-row\">\r\n");
      out.write("                                <div class=\"info-label\">Phone:</div>\r\n");
      out.write("                                <div>");
      out.print( order.getCustomer().getTelephone() );
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"info-section\">\r\n");
      out.write("                        <h3>📋 Order Information</h3>\r\n");
      out.write("                        <div class=\"info-row\">\r\n");
      out.write("                            <div class=\"info-label\">Date:</div>\r\n");
      out.write("                            <div>");
      out.print( order.getOrderDate() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-row\">\r\n");
      out.write("                            <div class=\"info-label\">Status:</div>\r\n");
      out.write("                            <div>");
      out.print( order.getStatus() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-row\">\r\n");
      out.write("                            <div class=\"info-label\">Created By:</div>\r\n");
      out.write("                            <div>");
      out.print( order.getCreatedByUser().getFirstName() );
      out.write(' ');
      out.print( order.getCreatedByUser().getLastName() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3>🛒 Order Items</h3>\r\n");
      out.write("                <div class=\"table-container\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>Product</th>\r\n");
      out.write("                                <th>Quantity</th>\r\n");
      out.write("                                <th>Unit Price</th>\r\n");
      out.write("                                <th>Discount</th>\r\n");
      out.write("                                <th>Total</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 for (OrderItem item : order.getItems()) { 
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( item.getProduct().getTitle() );
      out.write(" by ");
      out.print( item.getProduct().getAuthor() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( item.getQuantity() );
      out.write("</td>\r\n");
      out.write("                                    <td>$");
      out.print( String.format("%.2f", item.getUnitPrice()) );
      out.write("</td>\r\n");
      out.write("                                    <td class=\"discount\">\r\n");
      out.write("                                        ");
 if (item.getDiscountPercentage() > 0) { 
      out.write("\r\n");
      out.write("                                            ");
      out.print( item.getDiscountPercentage() );
      out.write("%\r\n");
      out.write("                                        ");
 } else { 
      out.write("\r\n");
      out.write("                                            -\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>$");
      out.print( String.format("%.2f", item.getUnitPrice() * item.getQuantity() * (1 - (item.getDiscountPercentage() / 100))) );
      out.write("</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                        <tfoot>\r\n");
      out.write("                            <tr class=\"total-row\">\r\n");
      out.write("                                <td colspan=\"4\" style=\"text-align: right;\">Total:</td>\r\n");
      out.write("                                <td>$");
      out.print( String.format("%.2f", order.getTotalAmount()) );
      out.write("</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tfoot>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"actions\">\r\n");
      out.write("                    <button onclick=\"window.print()\" class=\"btn btn-print no-print\">🖨️ Print Bill</button>\r\n");
      out.write("                    <a href=\"ManageOrdersServlet\" class=\"btn btn-primary no-print\">📋 Back to Orders</a>\r\n");
      out.write("                    <a href=\"admin_dashboard.jsp\" class=\"btn btn-secondary no-print\">🏠 Back to Dashboard</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
